# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='facebook',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='session',
            name='twitter',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
