# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160116_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('a', 'approved'), ('s', 'submitted'), ('r', 'rejected')], default='s', max_length=1),
        ),
    ]
