# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('a', 'approved'), ('s', 'submitted'), ('r', 'rejected')], max_length=1),
        ),
    ]
