# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Queestion',
            new_name='Question',
        ),
    ]
